[package]
name = "fastsheet"
version = "0.1.0"

[package.metadata.thermite]
github_releases = true
github_release_type = "latest"

[lib]
name = "fastsheet"
crate-type = ["cdylib"]

[dependencies]
ruru = "0.9.3"
lazy_static = "0.2.1"
calamine = "0.11.8"
